INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(1, 'The Secret Adversary', 'Agatha Christie', 10);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(2, 'The Left Hand of Darkness', 'Ursula K Le Guin', 6);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(3, 'Ubik', 'Philip K Dick', 4);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(4, 'And Then There Were None', 'Agatha Christie', 11);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(5, 'Charlie and the Chocolate Factory', 'Roald Dahl', 7);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(6, 'The Colour of Magic', 'Terry Pratchett', 0);
INSERT INTO BOOKS(ID, NAME, AUTHOR, BOOK_COUNT) VALUES(7, 'Charlie and the Great Glass Elevator', 'Roald Dahl', 4);

INSERT INTO USERS(ID, NAME, JOIN_DATE, HELD_BOOKS_COUNT) VALUES(1, 'Anna', '2023-08-13', 2);

INSERT INTO BOOKS_USERS(USER_ID, BOOK_ID) VALUES(1, 3);
INSERT INTO BOOKS_USERS(USER_ID, BOOK_ID) VALUES(1, 6);